### ISSUE TITLE
Utiliser le package subfiles

### ISSUE THREAD

**Issue by vvvictoire** [vvvictoire/memoire-meef#4]

**Comment by vvvictoire** [comment]
Du coup comme tu utilises Overleaf, tu veux toujours qu'on utilise subfiles ?

**Comment by vvvictoire** [comment]
D'ailleurs Overleaf pro c'est 7€/mois, avec plusieurs collaborateurs possibles dessus. À la limite on se cotise et c'est marre non ?

**Comment by Xaviere-EN** [comment]
En fait j'utilise un mix de SublimeText et Overleaf. Overleaf c'est juste pour vérifier que la compilation foire pas avant de push. Et travailler sur le mémoire sans me prendre la tête à la fac, vu que j'ai juste besoin de mon téléphone.
Le package subfiles c'est comme vous le souhaitez. J'ai souvenir qu'avec il faut redéfinir des chemins pour les images et la biblio sinon le fichier ne compile pas. Avec input, il n'y a pas ce soucis. Je l'utilisais sur mon rapport de stage parce que je gagnais du temps à la compilation avec (deux-trois commandes pratiques) mais on était vraiment en période de rush à l'époque, maintenant la contrainte temps a disparu.

J'attends l'avis de Julia, et si vous de votre coté ça vous convient comme ça, on reste comme ça. J'attends l'avis de Julia et je ferme.

Pour Overleaf pro, je sais pas. J'attends qu'ils fassent une offre à la pastebin (membership illimité). En plus, toi t'en as pas spécialement besoin.

**Comment by HuLijin** [comment]
Je pense qu'on peut clôturer cette issue. Avec la pratique, ce qui me plaisait avec subfiles, je l'ai retrouvé avec le fichier maitre sur overleaf.
@vvvictoire je ne peux pas clôturer il semblerait.
