### ISSUE TITLE
Générer un lien vers le vernier pdf

### ISSUE THREAD

**Issue by vvvictoire** [vvvictoire/memoire-meef#6]
Regarder s'il n'y a pas moyen de faire ça directiment avec travis

**Comment by Xaviere-EN** [comment]
Pendant la phase rédaction, je ne suis pas sûre que ça vaille le coup.
Pour la version finale, je linkerai directement le dernier PDF sur le site, non ?

**Comment by vvvictoire** [comment]
Bah les releases c'est un joyeux bordel, la dernière release n'est pas forcément celle qui est située en haut de page…

**Comment by vvvictoire** [comment]
J'ai peut-être trouvé une solution qui convient en tag automatiquement tout ce qu'on fait avec un nom de tag qui est mieux triable. À voir.

**Comment by vvvictoire** [comment]
Bon au final j'ai implémenté cette solution, qui fonctionne gloablement. Les releases ont l'air d'être dans l'ordre correct.
