### ISSUE TITLE
Faire un check d'orthographe et de grammaire avec grammalecte

### ISSUE THREAD

**Issue by vvvictoire** [vvvictoire/memoire-meef#7]
https://grammalecte.net/
Je fais des tests en local pour voir ce que ça donne, mais ça marche pas super super avec le LaTeX j'ai l'impression…

**Comment by Xaviere-EN** [comment]
Perso, je me fais plus confiance que je fais confiance en ce genre de logiciels. Y compris pour la typographie française qui est particulière et parfois mal prise en compte (babel fait un bon taf d'ailleurs sur les espaces insécables et certains caractères propres à notre langue). Les erreurs qui restent (tiret demi-cadratin au lieu du tiret d'union ou le caractère spécial pour les points de suspension par exemple) la plupart des gens ne voient même pas la différence.

**Comment by vvvictoire** [comment]
Non en fait non, ça va être trop relou à mettre en place. Tant pis, on fera confiance à nos yeux et nos relecteurs !
