### ISSUE TITLE
Help beamer : plus de bold en TeLaTex ou LuLaTex

### ISSUE THREAD

**Issue by JujuDem** [vvvictoire/memoire-meef#8]
Hello :)

En compilant avec XeLaTex il n'y a en effet pas de souci d'encodage des caractères, en revanche on perd la mise en gras ou en italique du texte. Je ne trouve pas de solution sur tex.stackexchange.com et autres forum donc je vous embête avec ça. Si vous ne savez pas, je me débrouillerai !

Julia

**Comment by vvvictoire** [comment]
C'est réglé 8)

**Comment by JujuDem** [comment]
merciiii
